title: Open Embeddings
description: "Publish for AI at internet scale."
baseurl: ""
url: "http://open-embeddings.org"

theme: minima

email: feedback@open-embeddings.org
twitter_username: openembeddings
github_username: open-embeddings
buymeacoffee_username: openembeddings

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  consumers:
    output: true
  publishers:
    output: true
  indexers-hub:
    output: true
collections_dir: pages

exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - _site/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - CLAUDE.md
  - claude.md
  - GEMINI.md

sass:
  quiet_deps: true
